### ISSUE TITLE
Build ARM version

### ISSUE THREAD

**Issue by RRosalia** [eilandert/dockerized#14]
Hey there all the images are currently hosted inside docker hub but I noticed there is no ARM version of any of the images. Can you please also build the images for ARM

**Comment by eilandert** [comment]
Hi

The problem is, I use/build my own packages mostly and I can't get them yet to build for ARM. It's on my wishlist but somehow crosscompiling is a no go. I can't test those packages either as I have no ARM.

NGINX is a different problem, it has a library (pagespeed) which is only available for AMD64, so I doubt it will make it to ARM

I hope to have some spare time soon
